import Head from "next/head";
import { Space } from "antd";

// styles
import styles from "../styles/Home.module.css";

// components
import { SimpleGreeting } from "./components/Greeting";
import { CircularProgress } from "./components/Progress";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <SimpleGreeting text={"Day"} />
        </div>
        <div>
          <SimpleGreeting text={"Night"} nightMode />
        </div>

        <div>
          <Space wrap>
            <CircularProgress />
          </Space>
        </div>
      </main>
    </>
  );
}
